def GUID="prima"
def CLUSTER = "na39.openshift.opentlc.com"
// Jenkinsfile for ParksMap
podTemplate(
  label: "skopeo-pod",
  cloud: "openshift",
  inheritFrom: "maven",
  containers: [
    containerTemplate(
      name: "jnlp",
      image: "docker-registry.default.svc:5000/${GUID}-jenkins/jenkins-slave-appdev",
      resourceRequestMemory: "1Gi",
      resourceLimitMemory: "2Gi"
    )
  ]
) {
  node('skopeo-pod') {
    echo "GUID: ${GUID}"
    echo "CLUSTER: ${CLUSTER}"

    // Your Pipeline Code goes here. Make sure to use the ${GUID} and ${CLUSTER} parameters where appropriate
    // You need to build the application in directory `ParksMap`.
    // Also copy "../nexus_settings.xml" to your build directory
    // and replace 'GUID' in the file with your ${GUID} to point to >your< Nexus instance

    def projectName="ParksMap"
    def mvnCmd = "mvn -s ./nexus_settings.xml -f ${projectName}/pom.xml"
    // def mvnCmd = "mvn"

    // Checkout Source Code
    stage('Checkout Source') {
      git url: "https://github.com/primashah/openshift_homework.git"
    }

    // The following variables need to be defined at the top level
    // and not inside the scope of a stage - otherwise they would not
    // be accessible from other stages.
    // Extract version and other properties from the pom.xml
    def groupId    = getGroupIdFromPom("${projectName}/pom.xml")
    def artifactId = getArtifactIdFromPom("${projectName}/pom.xml")
    def version    = getVersionFromPom("${projectName}/pom.xml")

    // Set the tag for the development image: version + build number
    def devTag  = "${version}-${BUILD_NUMBER}"
    // Set the tag for the production image: version
    def prodTag = "${version}"

    // Using Maven build the jar file
    stage('Build Parksmap Jar') {
      echo "Building version ${version}"
      sh "${mvnCmd} clean package spring-boot:repackage -DskipTests -Dcom.redhat.xpaas.repo.redhatga"
    }

    // run the unit tests
    stage('Unit Tests') {
      echo "Running Unit Tests"
      sh "${mvnCmd} test"
    }

    //  call SonarQube for Code Analysis
    stage('Code Analysis') {
      echo "Running Code Analysis"
      sh "${mvnCmd} sonar:sonar -Dsonar.host.url=http://docker-openshift-sonarqube-${GUID}-sonarqube.apps.${CLUSTER} -Dsonar.projectName=${JOB_BASE_NAME}-${devTag}"
    }

    // Publish the built war file to Nexus
    stage('Publish to Nexus') {
      echo "Publish to Nexus"
      sh "${mvnCmd} deploy -DskipTests=true -DaltDeploymentRepository=nexus::default::http://nexus3.${GUID}-nexus.svc.cluster.local:8081/repository/releases"
    }

     // Build the OpenShift Image in OpenShift and tag it.
    stage('Build and Tag OpenShift Image') {
      echo "Building OpenShift container image parksmap:${devTag}"

      // Start Binary Build in OpenShift using the file we just published
      sh "oc start-build parksmap --follow --from-file=./${projectName}/target/parksmap.jar -n ${GUID}-parks-dev"

      // Tag the image using the devTag
      openshiftTag alias: 'false', destStream: 'parksmap', destTag: devTag, destinationNamespace: "${GUID}-parks-dev", namespace: "${GUID}-parks-dev", srcStream: 'parksmap', srcTag: 'latest', verbose: 'false'
    }

    // Deploy the built image to the Development Environment.
    stage('Deploy to Dev') {
      echo "Deploying container image to Development Project"
      // Update the Image on the Development Deployment Config
      sh "oc set image dc/parksmap parksmap=docker-registry.default.svc:5000/${GUID}-parks-dev/parksmap:${devTag} -n ${GUID}-parks-dev"

      // Deploy the development application.
      openshiftDeploy depCfg: 'parksmap', namespace: "${GUID}-parks-dev", verbose: 'false', waitTime: '', waitUnit: 'sec'
      openshiftVerifyDeployment depCfg: 'parksmap', namespace: "${GUID}-parks-dev", replicaCount: '1', verbose: 'false', verifyReplicaCount: 'false', waitTime: '', waitUnit: 'sec'
      openshiftVerifyService namespace: "${GUID}-parks-dev", svcName: 'parksmap', verbose: 'false'
    }
     // Run Integration Tests in the Development Environment.
    stage('Integration Tests') {
      echo "Running Integration Tests"
      sh "curl http://parksmap.$GUID-parks-dev.svc.cluster.local:8080/ws/backends/list/"
      sh "curl http://parksmap.$GUID-parks-dev.svc.cluster.local:8080/ws/appname/"
    }

    // Copy Image to Nexus Docker Registry
    stage('Copy Image to Nexus Docker Registry') {
      echo "Copy image to Nexus Docker Registry"
      sh "skopeo copy --src-tls-verify=false --dest-tls-verify=false --src-creds openshift:\$(oc whoami -t) --dest-creds admin:admin123 docker://docker-registry.default.svc.cluster.local:5000/$GUID-parks-dev/parksmap:${devTag} docker://nexus-registry.$GUID-nexus.svc.cluster.local:5000/parksmap:${devTag}"

      // Tag the built image with the production tag.
      openshiftTag alias: 'false', destStream: 'parksmap', destTag: prodTag, destinationNamespace: "$GUID-parks-dev", namespace: "$GUID-parks-dev", srcStream: 'parksmap', srcTag: devTag, verbose: 'false'
    }

    // Blue/Green Deployment into Production
    // -------------------------------------
    def destApp   = "parksmap-green"
    def activeApp = ""
      
    stage('Blue/Green Production Deployment') {
      activeApp = sh(returnStdout: true, script: "oc get route parksmap -n $GUID-parks-prod -o jsonpath='{ .spec.to.name }'").trim()

      if (activeApp == "parksmap-green") {
        destApp = "parksmap-blue"
      }

      echo "Active Application:      " + activeApp
      echo "Destination Application: " + destApp

      sh "oc tag ${GUID}-parks-dev/parksmap:${devTag} ${GUID}-parks-prod/${destApp}:${prodTag}"
      //Creates image stream
      sh "oc set image dc/${destApp} ${destApp}=docker-registry.default.svc:5000/$GUID-parks-prod/${destApp}:${prodTag} -n $GUID-parks-prod"
    }
    

    

    

  }
}

// Convenience Functions to read variables from the pom.xml
// Do not change anything below this line.
def getVersionFromPom(pom) {
  def matcher = readFile(pom) =~ '<version>(.+)</version>'
  matcher ? matcher[0][1] : null
}
def getGroupIdFromPom(pom) {
  def matcher = readFile(pom) =~ '<groupId>(.+)</groupId>'
  matcher ? matcher[0][1] : null
}
def getArtifactIdFromPom(pom) {
  def matcher = readFile(pom) =~ '<artifactId>(.+)</artifactId>'
  matcher ? matcher[0][1] : null
}
